"""Daily NFL external-provider acquisition boundary."""

from daily_nfl.providers.contracts import (
    AcquisitionRequest,
    CostClass,
    DatasetKind,
    HistoricalAvailability,
    NormalizedAcquisition,
    NormalizedRecordProvenance,
    PointInTimeFidelity,
    ProviderAdapter,
    ProviderCapability,
    ProviderDescriptor,
    ProviderPayload,
    ReliabilityTier,
)
from daily_nfl.providers.metadata import (
    ProviderCapabilityConflictError,
    ProviderMetadataConflictError,
    RawEvidenceMetadataConflictError,
    RawEvidenceObservationConflictError,
    capability_id_for,
    record_provider,
    record_provider_capability,
    record_stored_acquisition,
)
from daily_nfl.providers.nflverse import (
    NFLVERSE_DESCRIPTOR,
    NflverseAdapter,
    UnsupportedDatasetError,
)
from daily_nfl.providers.nflverse_http import (
    NFLVERSE_RELEASE_BASE,
    NflverseAsset,
    NflverseHttpLoader,
    UnsupportedRawAssetMappingError,
    resolve_nflverse_assets,
)
from daily_nfl.providers.raw_store import (
    FileSystemRawEvidenceStore,
    RawEvidenceArtifact,
    RawEvidenceCollisionError,
    RawEvidenceStore,
    evidence_id_for,
    sha256_bytes,
)
from daily_nfl.providers.registry import ProviderRegistrationError, ProviderRegistry
from daily_nfl.providers.service import (
    AcquisitionService,
    StoredAcquisition,
    StoredEvidence,
    UnsupportedProviderCapabilityError,
    evidence_observation_id_for,
)

__all__ = [
    "AcquisitionRequest",
    "AcquisitionService",
    "CostClass",
    "DatasetKind",
    "FileSystemRawEvidenceStore",
    "HistoricalAvailability",
    "NFLVERSE_DESCRIPTOR",
    "NFLVERSE_RELEASE_BASE",
    "NflverseAdapter",
    "NflverseAsset",
    "NflverseHttpLoader",
    "NormalizedAcquisition",
    "NormalizedRecordProvenance",
    "PointInTimeFidelity",
    "ProviderAdapter",
    "ProviderCapability",
    "ProviderCapabilityConflictError",
    "ProviderDescriptor",
    "ProviderMetadataConflictError",
    "ProviderPayload",
    "ProviderRegistrationError",
    "ProviderRegistry",
    "RawEvidenceArtifact",
    "RawEvidenceCollisionError",
    "RawEvidenceMetadataConflictError",
    "RawEvidenceObservationConflictError",
    "RawEvidenceStore",
    "ReliabilityTier",
    "StoredAcquisition",
    "StoredEvidence",
    "UnsupportedDatasetError",
    "UnsupportedProviderCapabilityError",
    "UnsupportedRawAssetMappingError",
    "capability_id_for",
    "evidence_id_for",
    "evidence_observation_id_for",
    "record_provider",
    "record_provider_capability",
    "record_stored_acquisition",
    "resolve_nflverse_assets",
    "sha256_bytes",
]
