"""Provider-neutral Daily NFL domain contracts.

This package describes football concepts. Provider adapters and persistence
layers may populate these objects, but they must not redefine their semantics.
"""

from daily_nfl.domain.enums import (
    AvailabilityConfidence,
    AvailabilityMethod,
    GameResultType,
    GameStatus,
    ParticipationSide,
    PenaltyDisposition,
    PlayDesignModifier,
    PlayEventType,
    PlayType,
    SeasonPhase,
)
from daily_nfl.domain.game import (
    Game,
    GameResult,
    RulesetVersion,
    Season,
    SeasonWeek,
    Week,
)
from daily_nfl.domain.identity import (
    CoachingRole,
    Franchise,
    Person,
    Player,
    RosterStint,
    TeamSeason,
)
from daily_nfl.domain.ids import (
    CoachRoleId,
    CompetitionId,
    DepthChartSnapshotId,
    DriveId,
    EventId,
    FranchiseId,
    GameId,
    InjuryObservationId,
    ParticipationId,
    PenaltyId,
    PersonId,
    PlayerId,
    PlayEventId,
    PlayId,
    PossessionId,
    PossessionSegmentId,
    RosterStintId,
    TeamSeasonId,
    VenueId,
)
from daily_nfl.domain.play import (
    Drive,
    ObservedPhysicalOutcome,
    Participation,
    Penalty,
    Period,
    Play,
    PlayEvent,
    PlayExecution,
    PlayResult,
    PlayStateAfter,
    Possession,
    PossessionSegment,
    PrePlayState,
)
from daily_nfl.domain.temporal import KnowledgeTimestamp

__all__ = [
    "AvailabilityConfidence",
    "AvailabilityMethod",
    "CoachRoleId",
    "CoachingRole",
    "CompetitionId",
    "DepthChartSnapshotId",
    "Drive",
    "DriveId",
    "EventId",
    "Franchise",
    "FranchiseId",
    "Game",
    "GameId",
    "GameResult",
    "GameResultType",
    "GameStatus",
    "InjuryObservationId",
    "KnowledgeTimestamp",
    "ObservedPhysicalOutcome",
    "Participation",
    "ParticipationId",
    "ParticipationSide",
    "Penalty",
    "PenaltyDisposition",
    "PenaltyId",
    "Period",
    "Person",
    "PersonId",
    "Play",
    "PlayDesignModifier",
    "PlayEvent",
    "PlayEventId",
    "PlayEventType",
    "PlayExecution",
    "PlayId",
    "PlayResult",
    "PlayStateAfter",
    "PlayType",
    "Player",
    "PlayerId",
    "Possession",
    "PossessionId",
    "PossessionSegment",
    "PossessionSegmentId",
    "PrePlayState",
    "RosterStint",
    "RosterStintId",
    "RulesetVersion",
    "Season",
    "SeasonPhase",
    "SeasonWeek",
    "TeamSeason",
    "TeamSeasonId",
    "VenueId",
    "Week",
]
